package com.nakiplay.media

import android.app.Activity
import android.app.ActivityManager
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.os.PowerManager
import android.os.SystemClock
import android.view.WindowManager
import androidx.media3.common.util.UnstableApi
import androidx.media3.session.MediaController
import androidx.media3.session.SessionResult
import androidx.media3.session.SessionToken
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONObject
import org.junit.After
import org.junit.Assert.*
import org.junit.Assume.assumeTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.TimeUnit
import kotlin.math.sin

/** Exists only in the test APK. No debug commands/receivers are added to Naki Play. */
class PlaybackProbeActivity : Activity() {
    override fun onCreate(state: Bundle?) {
        super.onCreate(state)
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
    }
}

/** Runs on Android, not Robolectric or a resized desktop browser. */
@UnstableApi
@RunWith(AndroidJUnit4::class)
class NativeAudioPlaybackTest {
    private val instrumentation = InstrumentationRegistry.getInstrumentation()
    private val context get() = instrumentation.targetContext
    private val created = mutableListOf<File>()
    private lateinit var activity: Activity
    private var controller: MediaController? = null

    @Before fun connect() {
        shell("input keyevent KEYCODE_WAKEUP")
        shell("wm dismiss-keyguard")
        activity = instrumentation.startActivitySync(Intent(context, PlaybackProbeActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
        connectController()
        command("clear")
    }

    private fun connectController() {
        val future = onMain {
            MediaController.Builder(context, SessionToken(context, ComponentName(context, NakiAudioService::class.java))).buildAsync()
        }
        controller = future.get(20, TimeUnit.SECONDS)
    }

    @After fun cleanUp() {
        if (controller != null) runCatching { command("clear") }
        onMain { controller?.release(); controller = null }
        shell("input keyevent KEYCODE_WAKEUP")
        if (::activity.isInitialized) onMain { activity.finish() }
        // Only copies generated by this test in its own private application are removed.
        created.forEach { it.delete() }
    }

    private fun <T> onMain(block: () -> T): T {
        var result: Result<T>? = null
        instrumentation.runOnMainSync { result = runCatching(block) }
        return result!!.getOrThrow()
    }

    private fun command(action: String, args: Bundle = Bundle()): JSONObject {
        args.putString("action", action)
        val future = onMain { controller!!.sendCustomCommand(NakiAudioService.COMMAND, args) }
        val result = future.get(20, TimeUnit.SECONDS)
        assertEquals(result.extras.getString("error"), SessionResult.RESULT_SUCCESS, result.resultCode)
        return JSONObject(result.extras.getString("snapshot")!!)
    }

    private fun load(files: List<File>, current: File = files.first(), playing: Boolean = true, repeat: Boolean = false) = command("load", Bundle().apply {
        putParcelableArrayList("queue", ArrayList(files.map { file -> Bundle().apply {
            putString("id", file.name); putString("path", file.path); putString("title", file.name)
        } }))
        putString("currentId", current.name)
        putBoolean("playing", playing); putBoolean("repeatOne", repeat); putBoolean("autoplay", true)
        putBoolean("shuffle", false); putFloat("volume", 0.05f)
    })

    private fun awaitStatus(timeoutMs: Long = 15000, accept: (JSONObject) -> Boolean): JSONObject {
        val end = SystemClock.elapsedRealtime() + timeoutMs
        var status: JSONObject
        do {
            status = command("status")
            assertFalse(status.toString(), status.has("error"))
            if (accept(status)) return status
            SystemClock.sleep(200)
        } while (SystemClock.elapsedRealtime() < end)
        fail("Timed out waiting for playback: $status")
        return status
    }

    private fun copyAsset(name: String): File {
        assumeTrue("Optional local fixture missing: $name", instrumentation.context.assets.list("")!!.contains(name))
        val file = destination(name)
        instrumentation.context.assets.open(name).use { source -> file.outputStream().use { source.copyTo(it) } }
        return file
    }

    private fun destination(name: String): File {
        val root = File(context.dataDir, "media").apply { mkdirs() }
        return File(root, "probe-${System.nanoTime()}-$name").also { created.add(it) }
    }

    private fun tone(name: String, seconds: Int): File {
        val samples = 8000 * seconds
        val data = ByteBuffer.allocate(44 + samples * 2).order(ByteOrder.LITTLE_ENDIAN)
        data.put("RIFF".toByteArray()).putInt(36 + samples * 2).put("WAVEfmt ".toByteArray())
        data.putInt(16).putShort(1).putShort(1).putInt(8000).putInt(16000).putShort(2).putShort(16)
        data.put("data".toByteArray()).putInt(samples * 2)
        repeat(samples) { data.putShort((sin(it * 2.0 * Math.PI * 440 / 8000) * 1000).toInt().toShort()) }
        return destination(name).apply { writeBytes(data.array()) }
    }

    private fun shell(command: String) {
        instrumentation.uiAutomation.executeShellCommand(command).use { descriptor ->
            java.io.FileInputStream(descriptor.fileDescriptor).use { it.readBytes() }
        }
    }

    private fun playEntireFile(file: File, sleepScreen: Boolean) {
        assertTrue("Regression file must cross the old 1,024,000-byte transport boundary", file.length() > 1_024_000)
        load(listOf(file))
        val ready = awaitStatus { it.getBoolean("playing") && it.getLong("durationMs") > 220000 }
        val duration = ready.getLong("durationMs")
        val deadline = SystemClock.elapsedRealtime() + duration + 90000
        var previous = 0L
        var screenOff = false
        var disconnected = false
        while (SystemClock.elapsedRealtime() < deadline) {
            val status = command("status")
            assertFalse(status.toString(), status.has("error"))
            val position = status.getLong("positionMs")
            assertTrue("Unexpected rewind: $previous -> $position", position + 500 >= previous)
            previous = position
            if (sleepScreen && position >= 65000 && !screenOff) {
                shell("input keyevent KEYCODE_SLEEP")
                assertFalse((context.getSystemService(Context.POWER_SERVICE) as PowerManager).isInteractive)
                screenOff = true
            }
            if (screenOff && !disconnected) {
                onMain { controller!!.release(); controller = null }
                SystemClock.sleep(5000)
                connectController()
                disconnected = true
            }
            if (status.getString("state") == "ended") {
                assertTrue("Playback ended early: $status", position >= duration - 1500)
                if (sleepScreen) assertTrue("Screen-off stage was not reached", screenOff && disconnected)
                return
            }
            assertTrue("Unexpected pause: $status", status.getBoolean("playWhenReady"))
            SystemClock.sleep(1000)
        }
        fail("Full-file playback did not finish, last position=$previous duration=$duration")
    }

    @Test fun reportedOriginalPlaysToEndWithScreenOn() {
        playEntireFile(copyAsset("reported-original.mp3.mpeg"), sleepScreen = false)
    }

    @Test fun compatibleCopyPlaysToEndWithScreenOffAndControllerReconnect() {
        playEntireFile(copyAsset("reported-compatible.m4a"), sleepScreen = true)
    }

    @Test fun nativeQueueRepeatsCurrentThenAdvancesWhileScreenOff() {
        val first = tone("first.wav", 4)
        val second = tone("second.wav", 30)
        load(listOf(first, second), repeat = true)
        awaitStatus { it.getBoolean("playing") }
        command("seek", Bundle().apply { putLong("positionMs", 3500) })
        shell("input keyevent KEYCODE_SLEEP")
        SystemClock.sleep(1800)
        val repeated = command("status")
        assertEquals(first.name, repeated.getString("trackId"))
        assertTrue(repeated.toString(), repeated.getLong("positionMs") < 3000)
        command("options", Bundle().apply { putBoolean("repeatOne", false) })
        val next = awaitStatus { it.optString("trackId") == second.name && it.getLong("positionMs") > 1000 }
        assertTrue(next.getBoolean("playing"))
        assertFalse((context.getSystemService(Context.POWER_SERVICE) as PowerManager).isInteractive)
        @Suppress("DEPRECATION")
        val services = (context.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager).getRunningServices(100)
        assertTrue("Playback service must be foreground", services.any { it.service.className == NakiAudioService::class.java.name && it.foreground })
    }

    @Test fun queueEditsPreservePositionAndPrivateFileBoundary() {
        val first = tone("first.wav", 30)
        val second = tone("second.wav", 30)
        load(listOf(first, second), playing = false)
        awaitStatus { it.getString("state") == "ready" }
        command("seek", Bundle().apply { putLong("positionMs", 11000) })
        load(listOf(second, first), first, playing = false)
        val reordered = command("status")
        assertEquals(first.name, reordered.getString("trackId"))
        assertTrue(reordered.toString(), reordered.getLong("positionMs") in 10500..11500)
        val invalid = Bundle().apply {
            putString("action", "load")
            putParcelableArrayList("queue", arrayListOf(Bundle().apply { putString("id", "outside"); putString("path", "/sdcard/outside.mp3") }))
        }
        val result = onMain { controller!!.sendCustomCommand(NakiAudioService.COMMAND, invalid) }.get(10, TimeUnit.SECONDS)
        assertNotEquals(SessionResult.RESULT_SUCCESS, result.resultCode)
        assertEquals(first.name, command("status").getString("trackId"))
    }
}
